### PR TITLE
feat: dark mood

### PR DESCRIPTION
**Pull request by Damiloju**
**Description**

This PR proposes 3 moods for the blog(dark, light and sepia) and fixes a line-height issue with the headings.

Screenshot 2020-08-13 at 19 51 18

Screenshot 2020-08-13 at 19 51 53

Screenshot 2020-08-13 at 19 51 33

**Line Height Images**

Screenshot 2020-08-13 at 19 47 18

>Before

Screenshot 2020-08-13 at 19 49 08

>After

### CODE REVIEW

**Comment by lauragift21** [comment]
Thank you for sending this in @Damiloju! 🙏

Can I suggest dark black instead of blue? I'd like to see what that looks like 😊

**Comment by Damiloju** [comment]
Sure! @lauragift21 got a hex in mind?

**Comment by lauragift21** [comment]
Let's try this #030200 @Damiloju

**Comment by Damiloju** [comment]
Screenshot 2020-08-13 at 20 56 14

@lauragift21

**Comment by lauragift21** [comment]
This works and I'm not sure why the build is failing. 

I'll investigate that and merge it. Thanks again :)

**Pull request merged**
